// <auto-generated />
using System;
using ControlVehiculos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlVehiculos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251009134021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlVehiculos.Models.Entities.CentroInspeccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Centros");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Chequeo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chequeos");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.EstadoTurno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstadosTurno");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.EstadoVehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstadosVehiculo");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Evaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("int");

                    b.Property<Guid>("ResultadoEvaluacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InspectorId");

                    b.HasIndex("ResultadoEvaluacionId");

                    b.HasIndex("TurnoId")
                        .IsUnique();

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.EvaluacionDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChequeoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChequeoId");

                    b.HasIndex("EvaluacionId");

                    b.ToTable("EvaluacionDetalles");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Propietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.ResultadoEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ResultadosEvaluacion");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EstadoTurnoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoTurnoId");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("CentroId", "FechaHora")
                        .IsUnique();

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Anio")
                        .HasColumnType("int");

                    b.Property<Guid>("EstadoVehiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoVehiculoId");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.HasIndex("PropietarioId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Evaluacion", b =>
                {
                    b.HasOne("ControlVehiculos.Models.Entities.Usuario", "Inspector")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVehiculos.Models.Entities.ResultadoEvaluacion", "Resultado")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("ResultadoEvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVehiculos.Models.Entities.Turno", "Turno")
                        .WithOne("Evaluacion")
                        .HasForeignKey("ControlVehiculos.Models.Entities.Evaluacion", "TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inspector");

                    b.Navigation("Resultado");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.EvaluacionDetalle", b =>
                {
                    b.HasOne("ControlVehiculos.Models.Entities.Chequeo", "Chequeo")
                        .WithMany("EvaluacionDetalles")
                        .HasForeignKey("ChequeoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVehiculos.Models.Entities.Evaluacion", "Evaluacion")
                        .WithMany("Detalles")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chequeo");

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("ControlVehiculos.Models.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Turno", b =>
                {
                    b.HasOne("ControlVehiculos.Models.Entities.CentroInspeccion", "Centro")
                        .WithMany("Turnos")
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVehiculos.Models.Entities.EstadoTurno", "EstadoTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("EstadoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVehiculos.Models.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Turnos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("EstadoTurno");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.UsuarioRol", b =>
                {
                    b.HasOne("ControlVehiculos.Models.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlVehiculos.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Vehiculo", b =>
                {
                    b.HasOne("ControlVehiculos.Models.Entities.EstadoVehiculo", "EstadoVehiculo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("EstadoVehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVehiculos.Models.Entities.Propietario", "Propietario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoVehiculo");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.CentroInspeccion", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Chequeo", b =>
                {
                    b.Navigation("EvaluacionDetalles");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.EstadoTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.EstadoVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Evaluacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Propietario", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.ResultadoEvaluacion", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Turno", b =>
                {
                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ControlVehiculos.Models.Entities.Vehiculo", b =>
                {
                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
